server:
  port: 8080

spring:
  data:
    mongodb:
      uri: mongodb+srv://faviohuaman:whQVhuBsOgu0C0M4@cluster0.zkqvx.mongodb.net/PRS?retryWrites=true&w=majority
      database: PRS
  logging:
    level:
      org.springframework.r2dbc: DEBUG